/*
Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.

Example:

Input:
s = "abcd"
t = "abcde"

Output:
e

Explanation:
'e' is the letter that was added.
*/
class Solution {
public:
    char findTheDifference(string s, string t) {
        
        int arr[26] = {0}, brr[26] = {0}, i, j, size_s = s.size(), size_t = t.size();
        for( i = 0; i < size_s; i++ )
        {
            arr[s[i]-'a']++;
        }
        
        for( j = 0; j < size_t; j++ )
        {
            brr[t[j]-'a']++;
        }
        
        for( i = 0; i < 26; i++ )
        {
            if( arr[i] != brr[i] )
                break;
        }
        return ('a'+i);
    }
};
